Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,7 @@
 version: 2
 jobs:
+
+    # Build zipped extension
     build:
         docker:
             - image: ubuntu:16.04
@@ -12,15 +14,20 @@ jobs:
                   command: |
                       apt-get update
                       apt-get -y install zip
-                      apt-get install -y ca-certificates
+                      apt-get install -y ca-certificates jq
             - run:
                   name: 'Zip'
                   command: |
+                      mkdir build
                       zip -r ext.zip ./app
+                      cat ./app/manifest.json | jq -r '.version' >> ./build/version.txt
+#
             - persist_to_workspace:
                   root: /root/project
                   paths:
                       - ext.zip
+                      
+    # Publish build in Chrome store
     publish:
         docker:
             - image: cibuilds/chrome-extension:latest
@@ -42,12 +49,39 @@ jobs:
                           curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T /root/workspace/ext.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
                           curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
                       fi
+    
+    # Release on GitHub
+    release:
+        docker:
+            - image: cibuilds/github:0.12
+        steps:
+            - attach_workspace:
+                  at: /root/workspace
+            - run:
+                  name: "Check Workspace"
+                  command: |
+                      if test -d /root/workspace; then
+                          echo "Workspace attached!";
+                      else
+                          echo "Can't attach workspace"; exit 1
+                      fi
+#            - add_ssh_keys:
+#                  fingerprints:
+#                      - "xx"
+            - run:
+                  name: "Publish Release on GitHub"
+                  command: |
+                      export VERSION=$(cat /root/workspace/build/version.txt)
+                      ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -replace $VERSION /root/workspace/build
 
 workflows:
     version: 2
     commit-workflow:
         jobs:
-            - build
+            - build            
             - publish:
+                  requires:
+                      - build
+            - release:
                   requires:
                       - build
